# Generated by Django 6.0.5 on 2026-05-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('membership_start', models.DateField(auto_now_add=True)),
                ('membership_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('cardio', 'Кардио'), ('strength', 'Силовая'), ('yoga', 'Йога'), ('pilates', 'Пилатес')], max_length=50)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('workout_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('completed', 'Проведена')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api_v1.client')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api_v1.workout')),
            ],
            options={
                'unique_together': {('client', 'workout', 'workout_date')},
            },
        ),
    ]
